/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import Connection.ConnectionSerial;
import Connection.ListPorts;

import com.sun.javafx.scene.control.skin.VirtualFlow;
import gnu.io.CommPortIdentifier;
import gnu.io.NoSuchPortException;
import java.awt.Button;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.TooManyListenersException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.input.KeyCode.T;
import static javafx.scene.input.KeyCode.Y;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Ki Thuat 88
 */
public class App extends javax.swing.JFrame {
    ListPorts listPorts = new ListPorts();
    ConnectionSerial arduinoSerial;
    List<JLabel> listImage = new ArrayList<>();
    boolean flag;
    public App() {
        initComponents();
        init();
    }

    public void init() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        CommPortIdentifier portId = null;
        
        List<String> listAvailablePorts = listPorts.ListAvailablePorts();
        for (int i = 0; i < listAvailablePorts.size(); i++) {
            model.addElement(listAvailablePorts.get(i));
        }
        comboxConnect.setModel(model);
        ConnectionSerial arduinoSerial = new ConnectionSerial((String) comboxConnect.getSelectedItem());   
        addImage();
    }
    
    public void addImage(){
        listImage.add(jLabel2);
        listImage.add(jLabel3);
        listImage.add(jLabel4);
        listImage.add(jLabel5);
        listImage.add(jLabel6);
        listImage.add(jLabel7);
        listImage.add(jLabel8);
        listImage.add(jLabel9);
        listImage.add(jLabel10);
        listImage.add(jLabel11);
        listImage.add(jLabel2);
        listImage.add(jLabel3);
        listImage.add(jLabel14);
        listImage.add(jLabel15);
        listImage.add(jLabel16);
        listImage.add(jLabel17);       
    }
    
    public String changeDataFromArduino(String message){
        message = "";
        if(message.equals("o")){
            message = "Khu vực đang cháy";
            return message;
        }else if(message.equals("f")){
            message = "Khu vực bình thường";
            return message;
        }
        return message;
    }
    

    public void addValue2Table(String message) {
        DefaultTableModel model1 = new DefaultTableModel();
        tableData.setModel(model1);
        model1.addColumn("Khu vực");
        model1.addColumn("Trạng thái");
        String status = null;
        if(message != null && message.length() == 16){
        String [] value = message.split(""); // tách dữ liệu ra từng biến 1
        for(int i =0 ; i< value.length; i++){
            status = (value[i].equals("o")) ? "Khu vực đang cháy" : "Khu vực bình thường";
            if(status.equals("Khu vực đang cháy")){
                listImage.get(i).setIcon(new ImageIcon("C:\\Users\\Ki Thuat 88\\Documents\\NetBeansProjects\\App\\src\\Image\\fire.png"));
               
            }
             model1.addRow(new Object[] { "Khu vực " +(i+1), status});
        }    
       }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        connectData = new javax.swing.JButton(new ImageIcon("C:\\Users\\Ki Thuat 88\\Documents\\NetBeansProjects\\App\\src\\Image\\connectArduino.png"));
        labelConnect = new javax.swing.JLabel();
        comboxConnect = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaData = new javax.swing.JTextArea();
        btnConnectSever = new javax.swing.JButton("Kết nối Sever", new ImageIcon("C:\\Users\\Ki Thuat 88\\Documents\\NetBeansProjects\\App\\src\\Image\\connectSever.png"));
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton("Tắt Khẩn cấp", new ImageIcon("C:\\Users\\Ki Thuat 88\\Documents\\NetBeansProjects\\App\\src\\Image\\OffArduino.png"));
        jLabel1 = new javax.swing.JLabel();
        rKV1 = new javax.swing.JRadioButton();
        rKV2 = new javax.swing.JRadioButton();
        rKV3 = new javax.swing.JRadioButton();
        rKV4 = new javax.swing.JRadioButton();
        rKV5 = new javax.swing.JRadioButton();
        rKV6 = new javax.swing.JRadioButton();
        rKV7 = new javax.swing.JRadioButton();
        rKV8 = new javax.swing.JRadioButton();
        rKV9 = new javax.swing.JRadioButton();
        rKV10 = new javax.swing.JRadioButton();
        rKV11 = new javax.swing.JRadioButton();
        rKV12 = new javax.swing.JRadioButton();
        rKV13 = new javax.swing.JRadioButton();
        rKV14 = new javax.swing.JRadioButton();
        rKV15 = new javax.swing.JRadioButton();
        rKV16 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        connectData.setText("Kết nối");
        connectData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectDataActionPerformed(evt);
            }
        });

        labelConnect.setText("Kết nối tới");
        labelConnect.setIcon(new ImageIcon("C:\\Users\\Ki Thuat 88\\Documents\\NetBeansProjects\\App\\src\\Image\\device.png"));

        comboxConnect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        areaData.setColumns(20);
        areaData.setRows(5);
        jScrollPane2.setViewportView(areaData);

        btnConnectSever.setText("Kết nối Sever");
        btnConnectSever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectSeverActionPerformed(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Khu vực 1", null},
                {"Khu vực 2", null},
                {"Khu vực 3", null},
                {"Khu vực 4", null},
                {"Khu vực 5", null},
                {"Khu vực 6", null},
                {"Khu vực 7", null},
                {"Khu vực 8", null},
                {"Khu vực 9", null},
                {"Khu vực 10", null},
                {"Khu vực 11", null},
                {"Khu vực 12", null},
                {"Khu vực 13", null},
                {"Khu vực 14", null},
                {"Khu vực 15", null},
                {"Khu vực 16", null}
            },
            new String [] {
                "Khu vực 1", "Trạng thái"
            }
        ));
        tableData.setRowHeight(30);
        jScrollPane1.setViewportView(tableData);

        jButton1.setText("Tắt khẩn cấp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Xử lý khẩn cấp");
        jLabel1.setIcon(new ImageIcon("C:\\Users\\Ki Thuat 88\\Documents\\NetBeansProjects\\App\\src\\Image\\emergency.png"));

        buttonGroup1.add(rKV1);
        rKV1.setText("Khu vực 1");
        rKV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rKV1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rKV2);
        rKV2.setText("Khu vực 2");

        buttonGroup1.add(rKV3);
        rKV3.setText("Khu vực 3");

        buttonGroup1.add(rKV4);
        rKV4.setText("Khu vực 4");

        buttonGroup1.add(rKV5);
        rKV5.setText("Khu vực 5");

        buttonGroup1.add(rKV6);
        rKV6.setText("Khu vực 6");

        buttonGroup1.add(rKV7);
        rKV7.setText("Khu vực 7");

        buttonGroup1.add(rKV8);
        rKV8.setText("Khu vực 8");

        buttonGroup1.add(rKV9);
        rKV9.setText("Khu vực 9");

        buttonGroup1.add(rKV10);
        rKV10.setText("Khu vực 10");

        buttonGroup1.add(rKV11);
        rKV11.setText("Khu vực 11");

        buttonGroup1.add(rKV12);
        rKV12.setText("Khu vực 12");

        buttonGroup1.add(rKV13);
        rKV13.setText("Khu vực 13");

        buttonGroup1.add(rKV14);
        rKV14.setText("Khu vực 14");

        buttonGroup1.add(rKV15);
        rKV15.setText("Khu vực 15");

        buttonGroup1.add(rKV16);
        rKV16.setText("Khu vực 16");

        jLabel31.setText("jLabel18");

        jLabel32.setText("jLabel18");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboxConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(connectData, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConnectSever, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rKV1)
                                    .addComponent(rKV2)
                                    .addComponent(rKV3)
                                    .addComponent(rKV4)
                                    .addComponent(rKV5)
                                    .addComponent(rKV6)
                                    .addComponent(rKV7)
                                    .addComponent(rKV8)
                                    .addComponent(rKV9)
                                    .addComponent(rKV10)
                                    .addComponent(rKV11)
                                    .addComponent(rKV12)
                                    .addComponent(rKV13)
                                    .addComponent(rKV14)
                                    .addComponent(rKV15)
                                    .addComponent(rKV16))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 284, Short.MAX_VALUE)
                    .addComponent(jLabel31)
                    .addGap(0, 284, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 284, Short.MAX_VALUE)
                    .addComponent(jLabel32)
                    .addGap(0, 284, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connectData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConnectSever, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboxConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelConnect)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rKV15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(rKV16)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel31)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel32)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectDataActionPerformed
        // TODO add your handling code here:
        flag = true;
        arduinoSerial = new ConnectionSerial((String) comboxConnect.getSelectedItem()); 
        // kiểm tra xem người dùng đã chọn port nào !!!
        String newline = "\n";

        try {
            String check = arduinoSerial.initialize();
            // kiểm tra xem người dùng đã chọn cổng port đó trước chưa
            if (check.equals("0")) {
                areaData.setText("Đã thêm Port Thành công");
            } else if (check.equals("1")) {
                areaData.setText("Port bạn đã chọn");

            }
        } catch (NoSuchPortException ex) {
            Logger.getLogger(App.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        Thread thread = new Thread() {
            @Override
            public void run() {
                try {
                    arduinoSerial.startGetdata();
                    while (true) {
                        areaData.append(arduinoSerial.getInputLine() + newline);
                        addValue2Table(arduinoSerial.getInputLine());
                        Thread.sleep(1000);

                    }
                } catch (IOException ex) {
                    Logger.getLogger(App.class
                            .getName()).log(Level.SEVERE, null, ex);

                } catch (TooManyListenersException ex) {
                    Logger.getLogger(App.class
                            .getName()).log(Level.SEVERE, null, ex);

                } catch (InterruptedException ex) {
                    Logger.getLogger(App.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        thread.start(); 
    }//GEN-LAST:event_connectDataActionPerformed


    private void rKV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rKV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rKV1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:.
        if(flag){
        if(rKV1.isSelected()){
            arduinoSerial.send("1");
        }
        if(rKV2.isSelected()){
            arduinoSerial.send("1");
        }
        if(rKV3.isSelected()){
            arduinoSerial.send("1");
        }        
        if(rKV4.isSelected()){
            arduinoSerial.send("1");
        }       
        if(rKV5.isSelected()){
            arduinoSerial.send("1");
        }
        if(rKV6.isSelected()){
            arduinoSerial.send("1");
        }
        if(rKV7.isSelected()){
            arduinoSerial.send("1");
        }
        if(rKV8.isSelected()){
            arduinoSerial.send("1");
        }
        if(rKV9.isSelected()){
            arduinoSerial.send("1");
        }
        if(rKV10.isSelected()){
            arduinoSerial.send("1");
        }
        if(rKV11.isSelected()){
            arduinoSerial.send("1");
        }
        if(rKV12.isSelected()){
            arduinoSerial.send("1");
        }
        if(rKV13.isSelected()){
            arduinoSerial.send("1");
        }
        if(rKV14.isSelected()){
            arduinoSerial.send("1");
        }
        if(rKV15.isSelected()){
            arduinoSerial.send("1");
        }
        if(rKV16.isSelected()){
            arduinoSerial.send("1");
        }
        }else{
            areaData.setText("Chưa kết nối đến cổng vi điều khiển");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnConnectSeverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectSeverActionPerformed
        try {
            // TODO add your handling code here:
            Socket socketClient = new Socket("localhost", 1995);
            BufferedWriter sendData = new BufferedWriter(new OutputStreamWriter(socketClient.getOutputStream()));
            while (true) {
                String message = areaData.getText();
                sendData.write(message);
                sendData.newLine();
                sendData.flush();
            }
            //            sendData.close();
            //            socketClient.close();

        } catch (IOException ex) {
            Logger.getLogger(App.class
                .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConnectSeverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaData;
    private javax.swing.JButton btnConnectSever;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboxConnect;
    private javax.swing.JButton connectData;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelConnect;
    private javax.swing.JRadioButton rKV1;
    private javax.swing.JRadioButton rKV10;
    private javax.swing.JRadioButton rKV11;
    private javax.swing.JRadioButton rKV12;
    private javax.swing.JRadioButton rKV13;
    private javax.swing.JRadioButton rKV14;
    private javax.swing.JRadioButton rKV15;
    private javax.swing.JRadioButton rKV16;
    private javax.swing.JRadioButton rKV2;
    private javax.swing.JRadioButton rKV3;
    private javax.swing.JRadioButton rKV4;
    private javax.swing.JRadioButton rKV5;
    private javax.swing.JRadioButton rKV6;
    private javax.swing.JRadioButton rKV7;
    private javax.swing.JRadioButton rKV8;
    private javax.swing.JRadioButton rKV9;
    private javax.swing.JTable tableData;
    // End of variables declaration//GEN-END:variables
}
